const ROLES = {
	DEV: 'DEVELOPER',
	BA: 'BUSINESS_ANALYST',
	LEADER: 'LEADER',
	PO: 'PRODUCT_OWNER',
	ADMIN: 'ADMIN',
	HRM: 'HUMAN_RESOURCE_MANAGER',
	SUPERADMIN: 'SUPERADMIN',
	EMPLOYEE: 'EMPLOYEE'
}

const TASK_TYPE = {
  ANALYSIS: 'ANALYSIS',
  DBDIAGRAM: 'DBDIAGRAM',
  WIREFRAME: 'WIREFRAME',
  CODING: 'CODING',
  TESTING: 'TESTING',
  TRAINING: 'TRAINING',
  RnD: 'RnD',
  HOTFIX: 'HOTFIX',
  ADHOC: 'ADHOC'
}

const pipelineUser = [
	{
		$lookup: {
			from: 'hrm_users',
			localField: 'createdBy',
			foreignField: '_id',
			as: 'createdBy'
		}
	},
	{
		$unwind: {
			path: '$createdBy',
			preserveNullAndEmptyArrays: true
		}
	},
	{
		$lookup: {
			from: 'hrm_users',
			localField: 'updatedBy',
			foreignField: '_id',
			as: 'updatedBy'
		}
	},
	{
		$unwind: {
			path: '$updatedBy',
			preserveNullAndEmptyArrays: true
		}
	}
]

const settingsJson =
	'{"maxTaskDuration":24,"timeAutoStop1":{"hour":12,"minute":45,"second":0},"timeAutoStop2":{"hour":20,"minute":5,"second":0},"allowTimerBeforeApproved":false}'

const PERMISSIONS = {
	ACCOUNT_OVERRIDE: 'ACCOUNT_OVERRIDE',
	ACCOUNT_CREATE: 'ACCOUNT_CREATE',
	ACCOUNT_EDIT: 'ACCOUNT_EDIT',
	ACCOUNT_REMOVE: 'ACCOUNT_REMOVE',
	ACCOUNT_VIEW_ALL: 'ACCOUNT_VIEW_ALL',
	USER_OVERRIDE: 'USER_OVERRIDE',
	USER_CREATE: 'USER_CREATE',
	USER_EDIT_SELF: 'USER_EDIT_SELF',
	USER_REMOVE: 'USER_REMOVE',
	USER_VIEW: 'USER_VIEW',
	USER_VIEW_BY_SITE: 'USER_VIEW_BY_SITE',
	USER_PROFILE_REMOVE: 'USER_PROFILE_REMOVE',
	USER_PASSWORD_RESET_OTHER: 'USER_PASSWORD_RESET_OTHER',
	USER_PASSWORD_RESET_SELF: 'USER_PASSWORD_RESET_SELF',
	USER_EDIT_ALL: 'USER_EDIT_ALL',
	PROJECT_OVERRIDE: 'PROJECT_OVERRIDE',
	PROJECT_CREATE: 'PROJECT_CREATE',
	PROJECT_EDIT: 'PROJECT_EDIT',
	PROJECT_MEMBER_MANAGE: 'PROJECT_MEMBER_MANAGE',
	PROJECT_REMOVE: 'PROJECT_REMOVE',
	PROJECT_VIEW_ALL: 'PROJECT_VIEW_ALL',
	PROJECT_VIEW_SELF: 'PROJECT_VIEW_SELF',
	PROJECT_SETTING: 'PROJECT_SETTING',
	PERSONA_CREATE: 'PERSONA_CREATE',
	PERSONA_EDIT: 'PERSONA_EDIT',
	PERSONA_REMOVE: 'PERSONA_REMOVE',
	PERSONA_VIEW: 'PERSONA_VIEW',
	MILESTONE_CREATE: 'MILESTONE_CREATE',
	MILESTONE_EDIT: 'MILESTONE_EDIT',
	MILESTONE_REMOVE: 'MILESTONE_REMOVE',
	MILESTONE_VIEW: 'MILESTONE_VIEW',
	USERSTORY_CREATE: 'USERSTORY_CREATE',
	USERSTORY_EDIT: 'USERSTORY_EDIT',
	USERSTORY_REMOVE: 'USERSTORY_REMOVE',
	USERSTORY_VIEW_ALL: 'USERSTORY_VIEW_ALL',
	USERSTORY_APPROVE_LV1: 'USERSTORY_APPROVE_LV1',
	USERSTORY_APPROVE_LV2: 'USERSTORY_APPROVE_LV2',
	USERSTORY_DISAPPROVE_LV1: 'USERSTORY_DISAPPROVE_LV1',
	USERSTORY_DISAPPROVE_LV2: 'USERSTORY_DISAPPROVE_LV2',
	USERSTORY_CANCEL_NEED_APPROVE: 'USERSTORY_CANCEL_NEED_APPROVE',
	TASK_OVERRIDE: 'TASK_OVERRIDE',
	TASK_CREATE: 'TASK_CREATE',
	TASK_EDIT: 'TASK_EDIT',
	TASK_REMOVE: 'TASK_REMOVE',
	TASK_VIEW_ALL: 'TASK_VIEW_ALL',
	TASK_VIEW_SELF: 'TASK_VIEW_SELF',
	TASK_COMMENT: 'TASK_COMMENT',
	TASK_TIMING: 'TASK_TIMING',
	TASK_VIEW_DETAIL: 'TASK_VIEW_DETAIL',
	TASK_APPROVE: 'TASK_APPROVE',
	TASK_DISAPPROVE: 'TASK_DISAPPROVE',
	TASK_CANCEL_NEED_APPROVE_SELF: 'TASK_CANCEL_NEED_APPROVE_SELF',
	TASK_REVIEW: 'TASK_REVIEW',
	PERIOD_CREATE: 'PERIOD_CREATE',
	PERIOD_EDIT: 'PERIOD_EDIT',
	PERIOD_REMOVE: 'PERIOD_REMOVE',
	PERIOD_VIEW: 'PERIOD_VIEW',
	KPI_USER_VIEW: 'KPI_USER_VIEW',
	KPI_COMPANY_VIEW: 'KPI_COMPANY_VIEW',
	BONUS_CREATE: 'BONUS_CREATE',
	BONUS_EDIT: 'BONUS_EDIT',
	BONUS_REMOVE: 'BONUS_REMOVE',
	BONUS_VIEW: 'BONUS_VIEW',
	USER_CERTIFICATE_CREATE: 'USER_CERTIFICATE_CREATE',
	USER_CERTIFICATE_EDIT: 'USER_CERTIFICATE_EDIT',
	USER_CERTIFICATE_REMOVE: 'USER_CERTIFICATE_REMOVE',
	USER_CERTIFICATE_VIEW: 'USER_CERTIFICATE_VIEW',
	ROLE_CREATE: 'ROLE_CREATE',
	ROLE_EDIT: 'ROLE_EDIT',
	ROLE_REMOVE: 'ROLE_REMOVE',
	ROLE_VIEW: 'ROLE_VIEW',
	UNUSUAL_REPORT_VIEW: 'UNUSUAL_REPORT_VIEW',
	CONTRACT_CREATE: 'CONTRACT_CREATE',
	CONTRACT_EDIT: 'CONTRACT_EDIT',
	CONTRACT_REMOVE: 'CONTRACT_REMOVE',
	CONTRACT_VIEW: 'CONTRACT_VIEW',
	USERSTORY_NEED_APPROVE_EDIT: 'USERSTORY_NEED_APPROVE_EDIT',
	TASK_NEED_APPROVE_EDIT: 'TASK_NEED_APPROVE_EDIT'
}

export { pipelineUser, settingsJson, PERMISSIONS, ROLES, TASK_TYPE }
